### ISSUE TITLE
Potentially minor bug with sync type

### ISSUE THREAD

**Issue by zamlz** [erpalma/throttled-overlay#7]
I was updating portage and I got this message. I'm not sure how consequential it is however since my `emerge --sync` still updates this overlay properly.

```
!!! Repository 'throttled' has sync-type attribute set to unsupported value: 'laymansync'
!!! Installed sync-types are: '['cvs', 'git', 'rsync', 'svn', 'webrsync']'
```

I could even be a problem with layman, I'm not sure, I haven't explored the issue enough yet, but figured I'd post it just in case.

**Comment by erpalma** [comment]
Nope, it seems like a layman bug!

https://bugs.gentoo.org/627930

**Comment by zamlz** [comment]
Thanks for looking into it!
